// car rentals
export const SEARCH_CAR_RENTALS = 'SEARCH_CAR_RENTALS';
export const SEARCH_CAR_RENTALS_ERROR = 'SEARCH_CAR_RENTALS_ERROR';
export const SEARCH_CAR_RENTALS_RESPONSE = 'SEARCH_CAR_RENTALS_RESPONSE';
